### ISSUE TITLE
Define framework for building feature matrix for client libraries

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#38]
Moved from https://github.com/jaegertracing/jaeger/issues/384

## Problem

Jaeger already has 6 official client libraries, with different levels of support for different features. Ideally we want to standardize on a uniform set of features across all languages, but in practice some libs will be lagging behind others, so it would be good to have a feature matrix in the documentation.

## Proposal

Define feature matrix in a YAML file `data/clients.yaml` like this:

```yaml
features:
  - name: udp_jaeger_thrift
    description: Report spans in `jaeger.thrift` format over UDP
  - name: propagation_b3
    description: Support Zipkin's B3 headers as wire format for span context

clients:
  - name: Go
    repo: http://github.com/jaegertracing/jaeger-client-go
    features:
      udp_jaeger_thrift: Y
      propagation_b3: partial
  - name: Java
    repo: http://github.com/jaegertracing/jaeger-client-java
    features:
      udp_jaeger_thrift: Y
      propagation_b3: N
```

Ideally, the values in the fields like `description` (or all fields) would support Markdown.

## Open questions
  * can the template for rendering the table be written directly in `clients.md`?
  * if not, where do we define the template and how can we inline it in `clients.md`?

@lucperkins appreciate your input
